auth:
  handler:
    email_verification:
      request:
        error:
          invalid_intent_type: '無効な種別です。'
  usecase:
    create_session:
      invalid_email_password: 'メールアドレスまたはパスワードが正しくありません。'
    refresh_session:
      invalid_refresh_token: 'リフレッシュトークンが無効です。'
    delete_session:
      invalid_access_refresh_token: "認証情報が無効です。"
    request_email_verification:
      title: '確認コードの発行'
      header: 'メール路銀の確認コードが発行されました。'
      body: |-
        メールログインの確認コードが発行されました。
        表示されている画面に確認コードを入力してください。
        
        {{.Code}}
        
        有効期限は発行から{{.ExpiresInMinute}}です。
        このメールに心当たりがない場合は、無視していただいて構いません。
      error:
        email_already_exists: 'このメールアドレスは既に登録されています。'
        email_not_found: 'このメールアドレスは登録されていません。'
    reset_password:
      error:
        email_verification_invalid_token: '無効なメールアドレス認証トークンです。'
        email_verification_already_consumed: '再度メールアドレス認証を行ってください'
    verify_email:
      error:
        invalid_pin_code: '無効な PIN コードです。'

common:
  format:
    minute: '{{.Minute}}分'
  request:
    error:
      invalid_s3_object: '無効な S3 オブジェクトです。'
  handler:
    error:
      internal: 'ただいまアクセスが集中しております。しばらくしてから再度お試しください。'

message:
  usecase:
    create_message:
      email:
        subject: '{{ .SenderName }}からメッセージを受信しました'
        body: |-
          {{ .SenderName }}からメッセージを受信しました。
          
          「{{ .Content }}」

oauth:
  handler:
    error:
      invalid_provider_type: "無効な OAuth プロバイダです。"

registration:
  usecase:
    create_account:
      error:
        email_already_exists: 'このメールアドレスは既に登録されています。'
    create_password:
      error:
        email_verification_invalid_token: '無効なメールアドレス認証トークンです。'
        email_verification_already_consumed: '再度メールアドレス認証を行ってください'

user:
  model:
    user:
      error:
        slug_already_exists: 'このリンクは既に使用されています。'
        email_already_exists: 'このメールアドレスは既に使用されています。'
    user_attribute:
      error:
        duplicated: '既に登録済みです。'
  handler:
    user_link:
      error:
        invalid_provider_type: "無効なリンク提供業者です。"
  usecase:
    get_user:
      error:
        not_found: 'ユーザーが見つかりません。'
